MACOSX_DEPLOYMENT_TARGET: # [osx and x86_64]
  - "10.10"                # [osx and x86_64]
MACOSX_SDK_VERSION:       # [osx and x86_64]
  - "10.10"                # [osx and x86_64]
CONDA_BUILD_SYSROOT:
  # Downloaded from https://github.com/phracker/MacOSX-SDKs/releases
  - /opt/MacOSX10.10.sdk  # [osx]
